const CREATE = "CREATE";
const FETCH_POST = "FETCH_POST"
const FETCH_ALL = "FETCH_ALL";
const FETCH_BY_SEARCH = "FETCH_BY_SEARCH";
const UPDATE = "UPDATE";
const DELETE = "DELETE";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const START_LOADING = "START_LOADING";
const END_LOADING = "END_LOADING";




export {
    CREATE,FETCH_ALL,FETCH_BY_SEARCH,UPDATE,DELETE,
    AUTH,LOGOUT,START_LOADING,END_LOADING,FETCH_POST
}